name: SonarQube Scan

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  sonar-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: http://13.206.75.229:9000
        with:
          args: >
            -Dsonar.projectKey=time-tracker
            -Dsonar.sources=.
